name: release npm package
on:
  push:
    branches:
      - main
    paths:
      - packages/**

jobs:
  auto-release:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set releaser settings
        run: |
          git config --global user.name github-action
          git config --global user.email kcattdev@gmail.com

      - name: Set .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

      - name: Major release
        id: major
        run: npx -w packages release-it@15.6.0 -- major --ci
        if: contains(toJSON(github.event.commits.*.message), '🚀 bump up version major')

      - name: Minor release
        id: minor
        run: npx -w packages release-it@15.6.0 -- minor --ci
        if: steps.major.conclusion == 'skipped' && contains(toJSON(github.event.commits.*.message), '🚀 bump up version minor')

      - name: Patch release
        run: npx -w packages release-it@15.6.0 -- patch --ci
        if: "!(steps.major.conclusion == 'success' || steps.minor.conclusion == 'success')"
